In [1]:
import torch

# 三个 batch 的梯度
dL_dw = [
    (torch.tensor([1.]), torch.tensor([2.]), torch.tensor([3.])),
    (torch.tensor([10.]), torch.tensor([20.]), torch.tensor([30.])),
    (torch.tensor([100.]), torch.tensor([200.]), torch.tensor([300.])),
]

# 按位置相加
dL_dw_sum = [sum(grads) for grads in zip(*dL_dw)]

print(dL_dw_sum)
# 输出: [tensor([111.]), tensor([222.]), tensor([333.])]


[tensor([111.]), tensor([222.]), tensor([333.])]


In [4]:
for grads in zip(*dL_dw):
    print(grads)

(tensor([1.]), tensor([10.]), tensor([100.]))
(tensor([2.]), tensor([20.]), tensor([200.]))
(tensor([3.]), tensor([30.]), tensor([300.]))
